// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.categoryToolStripMenuItem1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.frmMain_FormClosing(System.Object,System.Windows.Forms.FormClosingEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.frmMain_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.itemToolStripMenuItem1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.ordersToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.positionToolStripMenuItem1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.transactionToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmMain.userToolStripMenuItem1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmUser.btnAdd_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmUser.btnUpdate_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmUser.dgvUsers_RowEnter(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmUser.frmUser_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmUser.txtSearch_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnAddItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnClose_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnDiscountItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnNewTransaction_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnPayment_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.btnRemoveItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.dgvCart_CellClick(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.dgvCart_CellValueChanged(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.enableButtons(System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.frmTransaction_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.loadAllItemsFromCart")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.newTransaction")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmTransaction.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmOrderDetail.setOrderDetail(System.Collections.Generic.List{POSWinforms.tblOrderDetail})")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmOrders.dgvOrders_CellClick(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmOrders.frmUser_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmOrders.loadAllOrders(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.frmOrders.txtSearch_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:POSWinforms.frmOrders")]
[assembly: SuppressMessage("CodeQuality", "IDE0076:Invalid global 'SuppressMessageAttribute'", Justification = "<Pending>")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.addMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.dgvItems_CellClick(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.dgvItems_CellDoubleClick(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.frmItem_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.loadAllItems(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.metroSetButton1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.metroSetButton2_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.metroSetButton3_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.selectItemMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Maintenance.frmItem.txtSearch_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.addToCart")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.btnAddToCart_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.btnSelectItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.discountSelector_KeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.discountSelector_ValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.frmAddItem_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.getGrandTotal(System.Decimal,System.Int32,System.Int32)~System.Decimal")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.quantitySelector_KeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.quantitySelector_ValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:POSWinforms.Transaction.frmSelectItem.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:POSWinforms.Maintenance.frmItem")]
